#!/bin/bash
. $(dirname $0)/conf

zfs create -o canmount=off -o mountpoint=none		${pool}/ROOT
zfs create -o canmount=noauto -o mountpoint=/ 	 	${pool}/ROOT/$root
zfs mount ${pool}/ROOT/$root
#zfs create                 -o setuid=off              	${pool}/home
zfs create -o mountpoint=/root                        	${pool}/root
zfs create -o canmount=off				${pool}/boot
zfs create 						${pool}/boot/grub
zfs create -o canmount=off -o setuid=off  -o exec=off 	${pool}/ROOT/$root/var
zfs create -o com.sun:auto-snapshot=false             	${pool}/ROOT/$root/var/cache
zfs create                                            	${pool}/ROOT/$root/var/spool
#zfs create                                            	${pool}/ROOT/$root/var/log
zfs create -o mountpoint=/var/log                      	${pool}/log
#zfs create -o com.sun:auto-snapshot=false -o exec=on  	${pool}/ROOT/$root/var/tmp
zfs create -o com.sun:auto-snapshot=false -o exec=on \
	   -o mountpoint=/var/tmp		  	${pool}/vtmp
zfs create -o com.sun:auto-snapshot=false -o exec=on \
	   -o mountpoint=/tmp		  		${pool}/tmp
zfs create -o com.sun:auto-snapshot=false \
           -o mountpoint=/var/lib/nfs                 	${pool}/ROOT/$root/var/nfs


zpool set bootfs=${pool}/ROOT/$root rpool
