#!/bin/bash
. $(dirname $0)/conf
for d in /dev /dev/pts /proc /sys /run; do
    mount --rbind $d ${dir}$d
done
rm $dir/etc/resolv.conf
cp /etc/resolv.conf $dir/etc/resolv.conf
echo $root > $dir/etc/debian_chroot

