#!/bin/bash -x
. $(dirname $0)/conf

cat > /etc/apt/sources.list <<!
deb http://archive.ubuntu.com/ubuntu $version main universe
deb-src http://archive.ubuntu.com/ubuntu $version main universe

deb http://security.ubuntu.com/ubuntu $version-security main universe
deb-src http://security.ubuntu.com/ubuntu $version-security main universe

deb http://archive.ubuntu.com/ubuntu $version-updates main universe
deb-src http://archive.ubuntu.com/ubuntu $version-updates main universe
!

rm /etc/mtab || true
ln -s /proc/self/mounts /etc/mtab
apt update

cat > /etc/fstab <<!
# /etc/fstab: static file system information.
#
# Use 'blkid' to print the universally unique identifier for a
# device; this may be used with UUID= as a more robust way to name devices
# that works even if disks are added and removed. See fstab(5).
#
# <file system>		<mount point>		<type>	<options>			<dump>	<pass>
proc			/proc			proc	nodev,noexec,nosuid		0	0
tmpfs			/run			tmpfs	noatime,nodev,nosuid,mode=1777	0	0
!

locale-gen en_GB.UTF-8
echo 'LANG="en_GB.UTF-8"' > /etc/default/locale

dpkg-reconfigure tzdata

#apt upgrade
apt install --yes ubuntu-minimal
apt install --yes --no-install-recommends linux-image-generic
apt install --yes zfsutils-linux zfs-initramfs openssh-server
modprobe zfs || true

addgroup --system lpadmin
addgroup --system sambashare

passwd


zfs set mountpoint=legacy ${pool}/var/log
zfs set mountpoint=legacy ${pool}/var/tmp
cat >> /etc/fstab << EOF
${pool}/var/log  		/var/log 		zfs 	defaults 		0	0
${pool}/var/tmp  		/var/tmp 		zfs 	defaults 		0	0
EOF
cat /etc/fstab
