#!/bin/bash
#!set -o nounset
#!set -o pipefail

me=$(dirname "$0")
GUESTS=
GUESTS="$*"
bootstrap=ubuntu/lxc_bootstrap

for guest in ${GUESTS}
do
	case ${guest} in
	# production
	alpha)	  args="--role=domain_controller --privileged --static=192.168.11.21" ;;
	bravo)	  args="--role=domain_controller --privileged --static=192.168.11.22" ;;
	echo)	  args="--role=puppet_master --puppet=master" ;;
	#juliet)   args="--role=router --vm --mac=00:16:3e:8d:d3:af --environment=development --boot=false" ;;
	#golf:juliet)   bootstrap="openwrt/lxc_bootstrap" args="--ip=192.168.11.251 --vpns=nord" ;;
	juliet)   args="--role=vpn_gateway --mac=00:16:3e:ea:ca:4d --environment=development --eth1=lxdbr0" ;;
	india)	  args="--role=iptv_server --mounts=media --mac=00:16:3e:93:c6:21 --nfs" ;;
	papa)	  args="--role=internet_gateway --mac=00:16:3e:fc:2a:87" ;;
	romeo)	  args="--role=vpn_gateway --mac";;
	router)	  args="--role=router";;
	#romeo)	  args="--role=router --privileged --mac=00:16:3e:fb:dc:5e" ;;
	#romeo)    bootstrap="openwrt/lxc_bootstrap" args="--ip=192.168.11.2 --vpns=privat boot=false" ;;
	tango)	  args="--role=media_server --privileged --nfs --mounts=net,home,media --gpu" ;;
	delta)	  args="--role=development --mounts=src,home --privileged --boot=false" ;;
	victor)	  bootstrap="openwrt/lxc_bootstrap" args="--vpns=privat --ip=192.168.11.252" ;;
	# testing
	lima)	  args="--boot=false --nesting=yes --privileged" ;;
	kilo)	  args="--role=generic_server --environment=development --boot=false" ;;
	sierra)	  args="--role=domain_controller --environment=development --boot=false" ;;
	november) args="--role=minimal_server --boot=false --environment=development" ;;
	yankee)   args="--role=minimal_server --boot=false --environment=development" ;;
	*)	  args="" ;;
	esac
	${me}/${bootstrap} ${args} ${guest}
done
