#!/bin/bash
set -x -e
host=${1:-golf}
root=${host}-1
pool=rpool
dir=/mnt
domain=theclarkhome.com
version=xenial
network=enp3s0

case ${host} in
foxtrot)
	boot=efi
	disks="
	/dev/disk/by-id/ata-SanDisk_SDSSDA120G_154715407711
	/dev/disk/by-id/ata-SanDisk_SDSSDA120G_164722461404 
	"
	;;
golf)
	disks="/dev/disk/by-id/ata-SanDisk_SDSSDA120G_164722459408"
	wholedisk=true
	boot=efi
	;;
test)
	pool=testpool
	disks="/test/1.img"
	;;
esac
ls -l ${disks}

declare -i count=0
for disk in ${disks}
do
	count+=1
done

echo $count
case ${count} in
1)	pooltype=;;
2)	pooltype=mirror;;
*)	echo "need to set pooltype" >&2; exit 1;;
esac

case ${boot} in
efi)	bootpart=-part9
	mkdosfsargs="-n EFI";;
*)	echo "need to set boot type" >&2; exit 1;;
esac

case ${wholedisk} in
true)	part=
	;;
*)	part=-part1
	mkdosfsargs="-F32 -n EFI"
	;;
esac
