#!/bin/bash


guest=${1}

if [ "${guest}" = "" ]
then
	echo usage: $0 guest
	exit 1
fi
if [ "${guest}" = "$(hostname)" ]
then
	command=""
else
	lxc info ${guest} >/dev/null 2>&1
	if [ $? -eq 0 ]
	then
		command="lxc exec ${guest} -- "
	else
		command="ssh ${guest} "
	fi
fi
set -x
# set up keys for backuppc
sudo ssh-keygen -f "/root/.ssh/known_hosts" -R ${guest}
sudo ssh-keygen -f "/etc/ssh/ssh_known_hosts" -R ${guest}
sudo -i -u backuppc ssh-keygen -f /var/lib/backuppc/.ssh/known_hosts -R ${guest}
sudo -i -u backuppc ssh-copy-id -i /var/lib/backuppc/.ssh/id_rsa.pub root@${guest}
echo "su to backuppc and run command"
echo "ssh -l root ${guest} whoami"
echo "sudo -i -u backuppc ssh -q -l root ${guest} whoami"
sudo -i -u backuppc ssh -q -l root ${guest} whoami
# general root keys
#sudo ssh-copy-id -i /root/.ssh/id_rsa.pub -f root@${guest}
#sudo $command ssh-keygen -f "/root/.ssh/known_hosts" -R foxtrot
#sudo $command ssh-copy-id -f root@foxtrot

