#!/bin/bash
set -o nounset
set -o pipefail
set -o errexit

. /etc/lsb-release
ARCH=amd64
domain=$(hostname -d)
ENVIRONMENT=production
guests=
host=$(hostname)
IP=
NETPLAN=disable_netplan
OSVERSION=${DISTRIB_CODENAME}
PUPPET=agent
ROLE=
SIZE=20GB

case $host in
foxtrot)  POOL=array
          puppetmaster=echo
          ;;
*)        POOL=default
          puppetmaster=foxtrot:echo
          ;;
esac

declare -A _configs _devices _mountconfig

_configs['boot']="boot.autostart 1"
_devices['root']="root disk path=/ pool=${POOL} size=${SIZE}"

_mountconfig['home']="disk path=/home source=/home recursive=true"
_mountconfig['media']="disk path=/srv/media source=/srv/media"
_mountconfig['public']="disk path=/srv/public source=/srv/public"
_mountconfig['src']="disk path=/usr/src source=/usr/src"
_mountconfig['net']="disk path=/net source=/net"

#bold() { echo echo -e "\e[32m$*\e[0m"; }
bold() { echo "$(tput smso)$*$(tput rmso)"; }

Usage()
{
  cat <<EOF >&2
$0: <flags> guests
Allowed flags are:
--arch=<arch> 			architecture [default = amd64]
--boot=<1|0> 			autostart container at boot [default = 1]
--environment=<environment> 	environment to use [default=production]
--gpu                           add gpu
--mounts                        List of comma separated mounts to add valid: ${!_mountconfig[@]}
--mac=<address>                 mac address
--nesting=<yes|no>		enable security nesting (for nested lxd) [default = no]
--nfs    		        allow nfs mounts
--privileged    		run guest in privileged mode 
--puppet=<master|agent|no>	bootstrap puppet [default = agent]
--raw=<value for raw.lxc>
--role=<role
--size=<value>			root disk size [default = 20GB]
--static=<ip>value>		static IP for interface
EOF
  exit 1
}

params="$(getopt -o h: --long arch:,boot:,environment:,gpu,mac:,mounts:,nesting:,nfs,privileged,puppet:,raw:,role:,size:,static:,version: --name "$0" -- "$@")"
eval set -- "$params"

while true
do
  case "$1" in
    --arch)	        ARCH=$2; shift 2 ;;
    --boot)		_configs['boot']="boot.autostart ${2}"; shift 2 ;;
    --environment)	ENVIRONMENT=$2; shift 2 ;;
    --gpu)      	_devices['gpu']="gpu gpu gid=44"; shift;;
    --mounts)	        IFS=',' read -r -a MOUNTS <<< "$2"; shift 2 ;;
    --mac)	        _configs['mac']="volatile.eth0.hwaddr ${2}"; shift 2;;
    --nesting)	        _configs['nesting']="security.nesting ${2}"; shift 2;;
    --nfs)
      _configs['nfs']='raw.apparmor "mount fstype=nfs,"'
      _configs['privileged']="security.privileged true"
      shift;;
    --privileged)	_configs['privileged']="security.privileged true"; shift;;
    --puppet)    	PUPPET=$2; shift 2 ;;
    --size)
      _devices['root']="root disk path=/ pool=${POOL} size=${2}"
      shift 2;;
    --raw)              _configs['raw']="raw.lxc ${2}"; shift 2;;
    --role)		ROLE=$2; shift 2 ;;
    --static)	        IP=$2; shift 2 ;;
    --version)	        OSVERSION=$2; shift 2 ;;
    --)		        shift; break ;;
    *)		        echo "Not implemented: $1" >&2;
                        exit 1 ;;
  esac
done

[[ $# -lt 1 ]] && Usage

guests=($@)

for guest in "${guests[@]}"
do
  bold "Create ${guest} with flags:"
  echo "ROLE=${ROLE}, ARCH=${ARCH}, PUPPET=${PUPPET}, IP=${IP} ENVIRONMENT=${ENVIRONMENT} OSVERSION=${OSVERSION} POOL=${POOL}"
  for MOUNT in "${MOUNTS[@]}"
  do
    _devices["${MOUNT}"]="${MOUNT} ${_mountconfig[${MOUNT}]}"
  done
  #bold "Configs:"; printf '%s\n' "${_configs[@]}"
  #bold "Devices:"; printf '%s\n' "${_devices[@]}"

  VERSION=images:ubuntu/${OSVERSION}/cloud/${ARCH}
  lxc init "${VERSION}" "${guest}" || true

  for config in "${!_configs[@]}"
  do
    lxc config set "${guest}" ${_configs[${config}]}
  done

  for device in "${!_devices[@]}"
  do
    lxc config device add "${guest}" ${_devices[${device}]}
  done

  # Now set cloud-init to install puppet agent
  lxc config set "${guest}" user.user-data - <<!
#cloud-config
apt:
  sources:
    puppet6:
      source: "deb http://apt.puppetlabs.com ${OSVERSION} puppet6"
      keyid: 7F438280EF8D349F
      keyserver: "https://apt.puppetlabs.com/DEB-GPG-KEY-puppet"

package_update: true
package_upgrade: true

puppet:
  package_name: puppet-agent
  conf_file: '/etc/puppetlabs/puppet/puppet.conf'
  ssl_dir: '/etc/puppetlabs/puppet/ssl'
  csr_attributes_path: '/etc/puppetlabs/puppet/csr_attributes.yaml'
  conf:
    agent:
      server: "${puppetmaster}.${domain}"
      environment: ${ENVIRONMENT}
  csr_attributes:
    extension_requests:
      pp_role: "${ROLE}"

packages:
  - openssh-server
!
#power_state:
#  delay: now
#  mode: reboot
#  message: Rebooting....
#  timeout: 30
#  condition: True

  lxc config show "${guest}"

  if [ "${IP}" != "" ]
  then
    lxc config set "${guest}" user.network-config - <<!
#cloud-config
network:
  version: 2
  ethernets:
    eth0:
      addressses: [ "${IP}"/24 ]
      gateway4: $(grep  gateway /etc/network/interfaces)
      nameservers:
        search: $(grep	dns-search /etc/network/interfaces)
        addresses: [ $(grep  dns-nameservers /etc/network/interfaces) ]
!
    sleep 2
  fi
  bold "Cleaning puppet cert"
  lxc exec ${puppetmaster} --env LANG="${LANG}" -- "$(dirname "$(which puppet)")"/puppetserver ca clean --certname "${guest}.${domain}" || true
  bold "Starting ${guest}"
  lxc start ${guest}
  sleep 1
  lxc exec "${guest}" -- cloud-init status --wait --long
  bold "Cloud-init complete, puppet agent run should be executing on ${guest}"

  case "${PUPPET}" in
  "agent")
    ;;
  "master")
    bold "Setting up puppet"
    lxc file push "$(dirname "$0")"/puppetmaster_bootstrap ${guest}///tmp/
    lxc exec ${guest} -- bash /tmp/puppetmaster_bootstrap
    if [[ ${NETPLAN} ]]
    then 
      lxc exec ${guest} -- apt -y install ifupdown net-tools
    fi
    ;;
  *)
    # allow time for dhcp and dns to catchup
    sleep 10
  esac

done
