#!/bin/bash
. $(dirname $0)/conf

echo $host >"${ALTROOT}"/etc/hostname
sed -i -e "1a 127.0.1.1       $host.$domain $host""${ALTROOT}"/etc/hosts
cat"${ALTROOT}"/etc/hosts

cat >>"${ALTROOT}"/etc/network/interfaces <<!
auto $network
iface $network inet dhcp
!
