#!/bin/bash
. $(dirname $0)/conf
for d in /dev /dev/pts /proc /sys /run; do
    mount --rbind $d ${dir}$d
done
rm"${ALTROOT}"/etc/resolv.conf
cp /etc/resolv.conf"${ALTROOT}"/etc/resolv.conf
echo $root >"${ALTROOT}"/etc/debian_chroot

