#!/bin/bash
. $(dirname $0)/conf
swap=/dev/zvol/${pool}/swap
declare -i _mult=50 # percentage value of RAM to make swap
declare -i SIZE=0
if [[ -e ${swap} ]]
then
	grep --silent $(readlink -f ${swap}) /proc/swaps && swapoff ${swap}
	zfs destroy -r ${pool}/swap
fi
SIZE=$(free --giga | awk '/^Mem:/{print $2}')
test -n ${SIZE} 
SIZE=$((SIZE*_mult/100))
zfs create -V ${SIZE} -b $(getconf PAGESIZE) -o compression=zle \
      -o logbias=throughput -o sync=always \
      -o primarycache=metadata -o secondarycache=none \
      -o com.sun:auto-snapshot=false ${pool}/swap

sleep 10
mkswap /dev/zvol/${pool}/swap 

sed -e "\%/dev/zvol/${pool}/swap%d" -i /etc/fstab
cat >> /etc/fstab <<!
/dev/zvol/${pool}/swap	none			swap	defaults		0	0
!
