#!/bin/bash
set -e
export host=${1}
export root=${host}-1
export pool=rpool
export dir=/mnt
export domain=theclarkhome.com
export version=xenial
export network=enp3s0
export BE=${pool}/ROOT/${root}
efipart=9
sgdisk="echo sgdisk"
export sgdisk="sgdisk"

if [[ ! ${host} ]] 
then
  echo "host cannot be empty" >&2
  exit 1
fi

wholedisk=true
boot=efi
wholedisk=true

declare -i count=${#DISKS[@]}

case "${host}" in
foxtrot|golf)
  if [[ ${count} -eq 0 ]]
  then
    echo "Disks should be been selected" >&1
    exit 1
  fi
  ;;
test)
  pool=testpool
  DISKS=("/test/1.img")
  ;;
esac
ls -l "${DISKS[@]}"


case ${count} in
1)	export pooltype=;;
2)	export pooltype=mirror;;
*)	echo "need to set pooltype" >&2; exit 1;;
esac

case ${boot} in
efi)	export bootpart=-part${efipart}
	export mkdosfsargs="-n EFI";;
*)	echo "need to set boot type" >&2; exit 1;;
esac

case ${wholedisk} in
true)	export part=
	;;
*)	export part=-part1
	export mkdosfsargs="-F32 -n EFI"
	;;
esac
set -x
